name: pm_app
description: "Product management"
publish_to: 'none'

version: 1.1.0+2

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  flutter_secure_storage: ^9.2.2
  stomp_dart_client: ^2.1.0
  file_picker: ^10.3.8
  url_launcher: ^6.3.2
  path_provider: ^2.1.2
  open_filex: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/splash.png
    - assets/icon.png

# ---------- SPLASH ----------
flutter_native_splash:
  android: true
  ios: true
  web: true

  # светлый фон сплеша
  color: "#FFFFFF"
  # картинка по центру
  image: assets/splash.png

  # Android 12+ (ОБЯЗАТЕЛЬНО отдельный блок)
  android_12:
    color: "#FFFFFF"
    image: assets/splash.png
    icon_background_color: "#FFFFFF"

# ---------- APP ICON ----------
flutter_launcher_icons:
  android: true
  ios: false
  image_path: assets/icon.png
  min_sdk_android: 21
  remove_alpha_ios: true
